spring.application.name=bikeservice

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/bikeservice
spring.datasource.username=root
spring.datasource.password=zoro123

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

app.jwt.secret=85dbe15d75ef9308c7ae0f33c7a324cc6f4bf519a2ed2f3027bd33c140a4f9aa
app.jwt.expiry-millis=900000